routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/threads', 'ThreadsController@index');
Route::post('/threads', 'ThreadsController@store');

Route::get('/threads/create', 'ThreadsController@create');

Route::get('/threads/{channel}', 'ThreadsController@index');
Route::get('/threads/{channel}/{thread}', 'ThreadsController@show');
Route::post('/threads/{channel}/{thread}/replies', 'RepliesController@store');

Route::post('/replies/{reply}/favorites', 'FavoritesController@store');

Route::get('/profiles/{user}', 'ProfilesController@show')->name('profile');

Route::delete('/threads/{channel}/{thread}', 'ThreadsController@destroy');

Route::delete('/replies/{reply}', 'RepliesController@destroy');
//Route::resource('threads', 'ThreadsController');


//Route::get('/threads/{thread}/replies', 'ThreadsController@store');

app/Thread.php
<?php

namespace App;

use App\Filters\ThreadFilters;
use Illuminate\Database\Eloquent\Scope;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Thread extends Model
{
    use RecordActivity;
    
    protected $guarded = [];

    protected $with = ['creater', 'channel'];

    protected static function boot()
    {
        parent::boot();
        /*
        */
        //$thread->withCount('replies')->find($thread->id);
        //글로벌 스코프 등록. boot 매소드는 모든 프레임워크 내 코어가 동작 된 후 호출 되며
        //프레임워크 내부 기능을 자유롭게 사용할수 있다.
        static::addGlobalScope('replyCount', function($builder) {
            $builder->withCount('replies');     
        });

        static::deleting(function($thread){
            $thread->replies->each->delete();
        });
    }

  
    /**
     * 리스트 a 태그 경로
     */
    public function path()
    {
        return "/threads/{$this->channel->slug}/{$this->id}";
    }

    /**
     * 리플
     */
    public function replies()
    {
        return $this->hasMany(Reply::class)->withCount('favorites')->latest();
    }

    /**
     * 리플 카운트
     */
    public function getReplyCountAttribute()
    {
        return $this->replies()->count();
    }

    /**
     * 작성자
     */
    public function creater()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    /**
     * 리플추가
     */
    public function addReply($reply)
    {   
        //dd($this->replies());
        $this->replies()->create($reply);
    }

    /**
     * 채널관계
     */
    public function channel()
    {
        return $this->belongsTo(Channel::class);
    }

    /**
     * 검색 필터
     */ 
    
    public function scopeFilter($query, ThreadFilters  $filters)
    {
        return $filters->apply($query);
    }
    
}

app/Http/Controllers/ThreadsController.php
<?php

namespace App\Http\Controllers;

use App\Thread;
use App\Channel;
use App\Filters\ThreadFilters;
use Illuminate\Http\Request;

class ThreadsController extends Controller
{
    
    //작성 부분만 권한 체크
    public function __construct()
    {
        //$this->middleware('auth')->only(['store', 'create']);
        $this->middleware('auth')->except(['index', 'show']);
    }
   
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Channel $channel, ThreadFilters $filters)
    {
        // 
        $threads = $this->getThread($channel, $filters);
        
        if(request()->wantsJson()) {
            return $threads;    
        }

        return view('threads.index', compact('threads'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('threads.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        //dd($request->all());
        
        $this->validate($request, [
            'title' => 'required',
            'body'  => 'required',
            'channel_id' => 'required|exists:channels,id'
        ]);

        $thread = Thread::create([
            'title'     => request('title'), 
            'body'      => request('body'),
            'user_id'   => auth()->id(),
            'channel_id' => request('channel_id')
        ]);

        return redirect($thread->path())
            ->with('flash', '쓰레드 등록이 완료 되었습니다.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function show($channel, Thread $thread)
    {
        //
        //return $thread->withCount('replies')->find($thread->id);
        //dd($thread->get());
        //return $thread->load('replies.favorites')->load('replies.owner');
        return view('threads.show', [
            'thread' => $thread,
            'replies' => $thread->replies()->paginate(4)  
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function edit(Thread $thread)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Thread $thread)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function destroy($channel, Thread $thread)
    {
        //
        $this->authorize('update', $thread);
            
        // if( $thread->user_id != auth()->id() ){
             
        //     if (request()->wantsJson()){
        //         return response(['status' => 'Permission Denied'], 403);     
        //     }

        //     return redirect('/login');
            

        //     abort(403, 'Yod do not have permission to do this.');
        // }
         
        //$thread->replies()->delete();
        $thread->delete();

        if (request()->wantsJson()) {
            return response([], 204);
        } 

        return redirect('/threads');        
    }


    protected function getThread(Channel $channel, ThreadFilters $filters)
    {
        $threads = Thread::latest()->filter($filters);

        if($channel->exists) {
            $threads->where('channel_id', $channel->id);
        }

        return $threads->get();
    }
}

resources/views/threads/create.blade.php
@extends('layouts.app')


@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Create a New Thread</div>
                        
                <div class="card-body">
                    <form method="post" action="/threads" >
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="channel_id">Choose a Channel:</label>
                            <select name="channel_id" id="channel_id" class="form-control" required >
                                <option value="">Choose one...</option>
                                @foreach(App\Channel::all()  as $channel) 
                                    <option value="{{$channel->id}}" {{old("channel_id") == $channel->id ? 'selected' : ''}}>{{$channel->slug}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="title">Title:</label>
                            <input type="text" class="form-control" id="title" name="title" placeholder="Title" value="{{ old('title') }}" required />
                        </div>
                        <div class="form-group">
                            <label for="body">Body:</label>
                            <textarea class="form-control" id="body" name="body" placeholder="" row="8" required>{{old('body')}}</textarea>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-default">Publish</button>
                        </div>
                        @if( count($errors) )
                            <ul class="alert alert-danger">
                                @foreach ($errors->all() as $error)
                                    <li>{{$error}}</li>
                                @endforeach
                            </ul>
                        @endif
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/threads/index.blade.php
@extends('layouts.app')


@section('content')
<div class="container">
    <div class="row justify-content-center">
        @forelse($threads as $thread)  
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <div class="level">
                            <h4 class="flex">
                                <a href="{{ $thread->path() }}">{{ $thread->title }}</a>
                            </h4>
                            <strong>
                                <a href="{{ $thread->path() }}">{{ $thread->replies_count }} {{str_plural('reply', $thread->replies_count)}}.</a>
                            </strong>
                        </div>
                    </div>        
                    
                    <div class="card-body">
                        <div>{{ $thread->body }}</div>
                    </div>
                </div>
            </div>
        @empty 
            <p>There are no relevant results as this time.</p>
        @endforelse
    </div>
</div>
@endsection

resources/views/threads/reply.blade.php
@foreach ($replies as $reply)
    <hr/>
    <div class="row " id="reply-{{$reply->id}}">
        <div class="col"> 
            <div class="card-header bg-warning">
                <div class="level">
                    <h6 class="flex">
                        <a href="{{route('profile', $reply->owner)}}"  >
                            {{ $reply->owner->name }}
                        </a>&nbsp;said {{ $reply->created_at->diffForHumans() }}...
                    </h6>
                    
                    <div>
                        <form method="POST" action="/replies/{{$reply->id}}/favorites">
                            {{csrf_field()}}
                            <button type="submit" class="btn btn-default" {{ $reply->isFavorited() ? 'disabled' : '' }}>
                                {{$reply->favorites()->count()}}&nbsp;{{str_plural('Favorite', $reply->favorites()->count())}}
                            </button>
                        </form>
                    </div>
                </div> 
            </div>
            <div class="card">
                <div class="card-body">
                    <div>{{ $reply->body }}</div>
                </div>
                @can ('update', $reply)
                    <div class="card-footer ">
                        <form method="POST" action="/replies/{{$reply->id}}"> 
                            {{csrf_field()}}
                            {{method_field('DELETE')}}
                            <button type="submit" class="btn  btn-danger btn-xs" >Delete</button>
                        </form>
                    </div>
                @endcan
            </div>
        </div>
    </div>
@endforeach
@if($replies->count() > 0)
    <hr>
    <div class="row justify-content-center">
        {{ $replies->links() }}
    </div>
@endif
<hr/>
@if(auth()->check())
    <div class="row ">
        <div class="col "> 
            <form method="POST" action="{{ $thread->path() }}/replies" > 
                {{csrf_field()}}
                <div class="form-group">
                    <textarea name="body" id="body" class="form-control" placeholder="Have Something to Say?" rows="5"></textarea>
                </div>
                <button type="submit"  class="btn btn-default">Post</button> 
            </form>
        </div>
    </div>
    <hr>
@else 
    <p class="text-center">Please <a href="{{route('login')}}">Sign In</a> to participate in this discussion.</p>
    <hr>
@endif

resources/views/threads/show.blade.php
@extends('layouts.app')


@section('content')
<div class="container">
    <div class="row ">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <div class="level">
                        <span class="flex">
                            <a href="{{route('profile', $thread->creater)}}"  >{{ $thread->creater->name }}</a> posted :  
                            {{ $thread->title }}
                        </span>

                        @can ('update', $thread)
                            <form action="{{$thread->path()}}" method="POST"> 
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}
                                
                                <button type="submit" class="btn btn-link">Delete Thread</button>
                            </form>
                        @endcan
                    </div>
                </div>
                        
                <div class="card-body">
                    <div>{{ $thread->body }}</div>
                </div>
            </div>
            @include ('threads.reply')
        </div>
        
        <div class="col-md-4">
             <div class="card">
                <div class="card-body">
                    This thread was published {{ $thread->created_at->diffForHumans() }} by 
                    <a href="/profiles/{{ $thread->creater->name }}" >{{ $thread->creater->name }} </a>  and currently 
                    has {{ $thread->replies_count }} <!--한개일떄 여러개일때 단수형 복수형-->{{str_plural('comment', $thread->replies_count)}}.
                </div>
            </div>
        </div>
    </div>
</div>
@endsection